export var ACTION_STATES;
(function (ACTION_STATES) {
    ACTION_STATES["NO_REQUEST"] = "NO_REQUEST";
    ACTION_STATES["SEND"] = "SEND";
    ACTION_STATES["SUCCESS"] = "SUCCESS";
    ACTION_STATES["FAILED"] = "FAILED";
})(ACTION_STATES || (ACTION_STATES = {}));
